# Generated by Django 5.1 on 2024-09-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch_of_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dd214',
            field=models.FileField(blank=True, null=True, upload_to='dd214/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='era',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='membership_card',
            field=models.FileField(blank=True, null=True, upload_to='membership_cards/'),
        ),
    ]
