# Generated by Django 5.1 on 2024-08-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('sponsorship_type', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sponsorship_duration', models.CharField(choices=[('One-Time', 'One-Time'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Lifetime', 'Lifetime')], max_length=20)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_address', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/')),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
