# Generated by Django 5.1 on 2024-09-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('relationship_to_veteran', models.CharField(max_length=100)),
                ('veteran_name', models.CharField(max_length=255)),
                ('students_in_high_school', models.IntegerField()),
                ('students_in_class', models.IntegerField()),
                ('cumulative_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gpa_scale', models.DecimalField(decimal_places=2, max_digits=4)),
                ('graduation_date', models.DateField()),
                ('transcript', models.FileField(blank=True, null=True, upload_to='transcripts/')),
                ('school_official_name', models.CharField(max_length=255)),
                ('school_official_title', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
